type: round_robin
port: 8080
backends:
  - address: http://127.0.0.1:8081
    alive: true
  - address: https://yahoo.com
    alive: false
  - address: https://google.com
    alive: true
  - address: https://bing.com
    alive: true
# backends:
#   - address: 127.0.0.1:8081
#     alive: true
#   - address: 127.0.0.1:8082
#     alive: true
