type: least_conn
port: 8080
backends:
  - address: http://localhost:8081
    alive: true
  - address: http://localhost:8082
    alive: true
# backends:
#   - address: https://yahoo.com
#     alive: false
#   - address: https://google.com
#     alive: true
#   - address: https://bing.com
#     alive: true
